### ISSUE TITLE
Pre-defined filtering in list page

### ISSUE THREAD

**Issue by Steven-Chan** [oursky/django-material-demo#14]
- dropdown
- multi-select
- checkboxes
- range slider
- date picker

**Comment by tung2744** [comment]
@Steven-Chan Would like to know if there are any planning on how to implement this?
Because django material seems only support filters in pro, so we will implement it on our own?

**Comment by Steven-Chan** [comment]
@tung2744 @Rubikium  in our another project there is filtering on the RHS of the list

<img width="823" alt="image" src="https://user-images.githubusercontent.com/12228201/189888189-172f437e-36d2-4c00-b497-d12e141bc031.png">

But the search bar is on top of the list, which i believe is added ourselves. If we follow the demo site http://demo.viewflow.io/employees/employees/, the search bar should also be put on the RHS.

I think this is one thing we need to study that how much more work is needed to put the search bar in a different place.

**Comment by tung2744** [comment]
@Steven-Chan I believe that is only available in PRO, as I looked into their source code and found there should be no way to configure those filters easily.
And another project here: https://github.com/oursky/fairwood/blob/dev/services/cms/cms/views/material.py#L96
You can see we make the filters manually.

**Comment by Steven-Chan** [comment]
@tung2744 I think it is unavoidable to include this in demo even if we need to implement ourselves, just like nesting form. This feature is too common. We will need to answer other colleagues questions on how much effort and complexity needed to the project if they need to add this feature.

**Comment by Steven-Chan** [comment]
I think the good news is, this feature is PRO only, which means we can implement this in the way that it originally designed. Don't need to design ourselves in the risk of breaking the framework design principle.
