### ISSUE TITLE
Remove django admin site

### ISSUE THREAD

**Issue by tung2744** [oursky/django-material-demo#48]
@Steven-Chan @Rubikium 
As I believe this demo if for demonstrating django material frontend, which is an alternative of django admin. Should we remove django admin paths and views from the project?

**Comment by Steven-Chan** [comment]
I think its fine to keep it if that's just a few lines of code? Maybe we can use it as reference for what the default admin site can do.

**Comment by tung2744** [comment]
ok, let me close it.
