### ISSUE TITLE
Display relational data

### ISSUE THREAD

**Issue by Steven-Chan** [oursky/django-material-demo#6]

**Comment by Rubikium** [comment]
I plan to display a follower count in the question list page, which is calculated from the follower relationship between users and questions.

**Comment by Steven-Chan** [comment]
> I plan to display a follower count in the question list page, which is calculated from the follower relationship between users and questions.

I don't think it matches the issue. This is more like data aggregation instead.

**Comment by Rubikium** [comment]
By default, the detail page shows:
- Object fields (`TextField`, `DateField`,...)
- Relational data with _single_ value (`ForeignKey`, `OneToOneField`)

Fields are listed in same order as in `model.py`, and all texts are html escaped before rendering.

The detail page **does not** show:
- Relational data with _multiple_ values (`ManyToManyField`)
- Reverse relations (fields identified by `related_name`, e.g.: `question_set`)

To show data with multiple values and customize what and how data is rendered, we could create a subclass of `DetailModelView` and overwrite its `get_object_data()` function which returns a generator of 2-tuples (key-value pairs). Use `django.utils.safestring.mark_safe()` to mark strings suitable for HTML rendering.
