### ISSUE TITLE
Relational data in edit page with inline edit

### ISSUE THREAD

**Issue by Steven-Chan** [oursky/django-material-demo#7]
- ordering

**Comment by Rubikium** [comment]
I will make the choices editable inline inside the question edit page, including adding and deleting choices

**Comment by Steven-Chan** [comment]
> I will make the choices editable inline inside the question edit page, including adding and deleting choices

This will demo one-to-many relationship. Could you help also include many-to-many?

**Comment by Rubikium** [comment]
In question follower:
- ordering
- enable_email_notify
- enable_sms_notify
